codecov:
  token: ${{ secrets.CODECOV_TOKEN }}
  bot: "codecov-io"
  ci:
    - "github.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  diable_default_path_fixes: no
  require_ci_to_pass: true
  notify:
    after_n_builds: 2
    wait_for_ci: yes
    
coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    # notification blocks. See: https://docs.codecov.io/docs/codecovyml-reference#section-coverage-notify
  status:
    project:
    patch:
    changes:
