name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]

    steps:
      - name: Set codecov token
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rspec spec
